### ISSUE TITLE
Check the Date of Next Episode for a Given TV Series

### ISSUE THREAD

**Issue by ogivuk** [ognjenvukovic/tv-aficionado#1]
**As a** user,
**I want to** see when is the next episode of a given TV series,
**so that** I know when to watch it.

# Description
Create a check for a single TV series with the result shown in a terminal.

# Acceptance criteria
A user can:
1. Provide the name of a TV show
2. See when is the next episode upon a manual execution of a script

# Tasks
1. [ ] Update SRS with the request
2. [ ] Design in the Architecture Document
3. [ ] Create Unit Tests
4. [x] Implement
5. [ ] Error handling
6. [ ] Parameters to config files
