### ISSUE TITLE
Update Documentation: Folder, Sprints, Board

### ISSUE THREAD

**Issue by ogivuk** [ognjenvukovic/tv-aficionado#6]
**As** an interested party/contributor/reviewer,
**I want to** be able to understand how the project applies SCRUM,
**so that** I can understand better how the project is run.

# Tasks
* [x] Rename the folder from /doc to /docs
* [x] Document how the Sprints are run
* [x] Document how the Board is run: Stories as enhancements, Tasks as a list item within its story, Stories moved between stages, Bugs as Bugs.
